theme: jekyll-theme-architect

repository: minzhang190/hawken

github:
    is_project_page: false
    is_user_page: false

plugins:
    - jekyll-redirect-from

title: Hawken LS Chinese
author: Zhang LaoShi
permalink: /:title

collections:
    year:
        output: true
    category:
        output: true

defaults:
    -
        scope:
            path: ""
            type: category
        values:
            layout: "category"
    -
        scope:
            path: ""
            type: year
        values:
            layout: "year"

google_analytics: UA-162759593-2
