theme: jekyll-theme-architect

repository: minzhang190/hawken

github:
    is_project_page: false
    is_user_page: false

title: Hawken LS Chinese
author: Zhang LaoShi
permalink: /:title

collections:
    category:
        output: true

defaults:
    -
        scope:
            path: ""
            type: category
        values:
            layout: "category"

google_analytics: UA-162759593-2
